### ISSUE TITLE
Upgrade to use nan 2+

### ISSUE THREAD

**Issue by vladtar** [kapetan/win-mouse#1]
Hi,

I would like to use this package (or more specifically `electron-drag`) for our electron app. The current version of electron uses io.js 3.3, which doesn't work with older versions of nan (<2). I was wondering if you would consider upgrading this package to use nan 2+.

Thank you.

**Comment by kapetan** [comment]
Didn't know electron updated the io.js version. I will take a look.

**Comment by vladtar** [comment]
Thank you. For your convenience nan release notes can be found here https://github.com/nodejs/nan/blob/master/CHANGELOG.md#200-jul-31-2015.

**Comment by kapetan** [comment]
I've updated both `win-mouse` and `osx-mouse` to use the newest version of `nan`. I also bumped the versions in `electron-drag`. 

I've tested with the newest electron version on OS X, but don't have the setup to test on windows.
