### ISSUE TITLE
error in installing...

### ISSUE THREAD

**Issue by eVanilla** [kapetan/win-mouse#11]
i got a error with MSB... and then i installed the microsoft-built-tools with npm and that fixed this problem but now i got this error ..

`X:\...\node_modules\win-mouse\build\addon.vcxproj(19,3): error MSB4019: The imported project "C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Micros oft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "X:\...\node_modules\win-mouse\build\addon.vcxproj" (default targets) -- FAILED.

Done Building Project "X:\...\node_modules\win-mouse\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"X:\...\node_modules\win-mouse\build\binding.sln" (default target) (1) ->
"X:\...\node_modules\win-mouse\build\addon.vcxproj" (default target) (2) ->
  X:\...\node_modules\win-mouse\build\addon.vcxproj(19,3): error MSB4019: The imported project "C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Micr osoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.12
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd X:\...\node_modules\win-mouse
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

this error means cant find this directory: ` "C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Micros oft.Cpp.Default.props"`
yes because this directory exist: ` "C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Micros oft.Cpp.Default.props"`
i really don't have any idea to fix this problem .. can anyone help me ?

**Comment by kapetan** [comment]
Did you resolve your issue. Do you have all the dependencies installed for node-gyp on windows?
