### ISSUE TITLE
Support node 12

### ISSUE THREAD

**Issue by ipy** [kapetan/win-mouse#14]
`win-mouse` uses `Handle` which is removed from the latest v8 version and causes build failure. Could be fixed like [node-iconv](https://github.com/bnoordhuis/node-iconv/pull/194) did.
![image](https://user-images.githubusercontent.com/2088040/54444449-af5b6f80-477d-11e9-9a23-78b60ad2a1c9.png)

ref:
https://github.com/nodejs/node/issues/25082

**Comment by fredski02** [comment]
I'm using the electron-drag npm package which uses win-mouse under the hood. I'm also getting a similar error when a npm post installer for my electron app runs `electron-builder install-app-deps ` and I'm using node -v =10.15.3. Did you manage to get your code working on a specific node version @ipy

**Comment by ipy** [comment]
Pushed a modified version for node 12 https://github.com/ipy/win-mouse

**Comment by robatwilliams** [comment]
Thank you, works great with Electron 5.0.1
