### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yuanyuZQ** [kapetan/win-mouse#17]
hi,I tried to install win-mouse,there is an error

![image](https://user-images.githubusercontent.com/22787985/67272747-b3a7f200-f4ef-11e9-80a2-fd06fd8f2ac5.png)
![image](https://user-images.githubusercontent.com/22787985/67272779-c5899500-f4ef-11e9-8d54-69661475ac87.png)

**Comment by yuanyuZQ** [comment]
i debt the reason is version diffirence,so,please Cound you tell me your node version,npm version,electron version and gyp version? tks

**Comment by kapetan** [comment]
I've never seen this issue. Hope you figured it out.
