### ISSUE TITLE
Merge osx and win mouse?

### ISSUE THREAD

**Issue by ahallicks** [kapetan/win-mouse#4]
Hi,

Thank for for this and osx-mouse. They are great modules and work perfectly with Electron. The only issue is I can't package my Electron app properly because on Windows the dependency on osx-mouse breaks and vice-versa on OSX.

So, not necessarily an issue, but is there a way to package the two into a single node_module that is environment-aware?

**Comment by kapetan** [comment]
You can create a module that does something like that. In [electron-drag](https://github.com/kapetan/electron-drag) I include `osx-mouse` and `win-mouse` as optional dependencies in `package.json`. So one (or maybe both) of them can fail to install, and I handle it at runtime with a `try/catch` around the `require` expression.
