### ISSUE TITLE
move osx-mouse and win-mouse together into one package

### ISSUE THREAD

**Issue by lukeapage** [kapetan/win-mouse#5]
1. I can't see you wanting one and not the other
2. remove dependency on try require
3. removes errors when installing
4. turns 2 optional dependencies into 1 dependency that is actually required
5. you don't get weird issues with shrinkwrap where if it is saved on windows it refuses to compile osx-mouse because it marked somehow in the shrinkwrap

We might be able to help - what do you think?

**Comment by lukeapage** [comment]
ah I see its a duplicate of #4 - so I am not the first hit by issues.

I know we can get round it - we've been using both - thanks for that - but its not ideal.

**Comment by lukeapage** [comment]
the real kicker is not being able to use shrinkwrap with these modules

**Comment by kapetan** [comment]
I rather keep them separate. But I was thinking if it's not possible to create a new node module and use git submodules to include `win-mouse` and `osx-mouse` as dependencies. That might require a new `binding.gyp` file.
