### ISSUE TITLE
'left-up' not always fired, and 'left-drag' keeps on firing

### ISSUE THREAD

**Issue by tex0l** [kapetan/win-mouse#6]
Hi,
I'm currently developing an app with electron  1.4.3 on Windows 10 running on VirtualBox 5.0.26 r108824 on OSX 10.11.6.

Sometimes (around one in 10, I have not found a specific step to reproduce) when I drag an drop a file on Windows, the `left-up` event is not fired, so that the `left-drag` event keeps on firing, whereas I'm only moving the mouse...

It is very problematic for me, has anyone got an idea on this ? I think (hope) it might come from the virtualization, but I have no actual PC to try it.

**Comment by ruiG** [comment]
this is fixed by https://github.com/kapetan/win-mouse/pull/12

**Comment by kapetan** [comment]
I've merged the pull-request, hopefully that fixes your issue.
