### ISSUE TITLE
Can't use it in win7

### ISSUE THREAD

**Issue by zjxpcyc** [kapetan/win-mouse#7]
Hello，i just have one   line
```javascript
var mouse = require('win-mouse')();
```

And error below:

App threw an error during load
Error: Could not locate the bindings file. Tried:
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\build\addon.node
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\build\Debug\addon.node

 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\build\Release\addon.no
de
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\out\Debug\addon.node
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\Debug\addon.node
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\out\Release\addon.node

 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\Release\addon.node
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\build\default\addon.no
de
 鈫?D:\yinc\frontend\frameless_app\node_modules\win-mouse\compiled\7.4.0\win32\x
64\addon.node
    at bindings (D:\yinc\frontend\frameless_app\node_modules\bindings\bindings.j
s:88:9)
    at Object.<anonymous> (D:\yinc\frontend\frameless_app\node_modules\win-mouse
\index.js:3:13)
    at Object.<anonymous> (D:\yinc\frontend\frameless_app\node_modules\win-mouse
\index.js:41:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Application\\nodejs\\node.exe" "D:\\Application\\nodejs\\node
_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE
npm ERR! frameless_app@1.0.0 start: `electron .`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the frameless_app@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frameless_app package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frameless_app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frameless_app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\yinc\frontend\frameless_app\npm-debug.log

win7 x64
ms-version=2015

**Comment by kapetan** [comment]
If you are using `win-mouse` with electron make sure to compile the module with the correct electron headers. Electron has guide on how to do that on their site.
